[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "."
  functions = "functions"

[dev]
  command = "python app.py"
  port = 8080
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/divina-l3"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-lighthouse"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; connect-src 'self';
    Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
